/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.main;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Alefe Lucas
 */
public class NovaConta extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public NovaConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoDeContaButtonGroup = new ButtonGroup();
        tudoPanel = new JPanel();
        tituloLabel = new JLabel();
        corpoNovaContaPanel = new JPanel();
        novaContaPanel = new JPanel();
        cpfLabel2 = new JLabel();
        cpfTextField2 = new JTextField();
        tipoContaLabel = new JLabel();
        tipoContaPanel = new JPanel();
        correnteRadioButton = new JRadioButton();
        poupancaRadioButton = new JRadioButton();
        depositoInicialLabel = new JLabel();
        depositoInicialTextField = new JTextField();
        vazioPanel4 = new JPanel();
        criaPanel = new JPanel();
        criaButton = new JButton();
        voltarButton2 = new JButton();
        vazioPanel5 = new JPanel();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco SSA");
        setPreferredSize(new Dimension(350, 340));
        setResizable(false);

        tudoPanel.setLayout(new BorderLayout());

        tituloLabel.setHorizontalAlignment(SwingConstants.CENTER);
        tituloLabel.setIcon(new ImageIcon(getClass().getResource("/br/com/senai/main/loco SSA.png"))); // NOI18N
        tudoPanel.add(tituloLabel, BorderLayout.PAGE_START);

        novaContaPanel.setBorder(BorderFactory.createTitledBorder(null, "Nova Conta:", TitledBorder.LEFT, TitledBorder.ABOVE_TOP, new Font("sansserif", 1, 18))); // NOI18N
        novaContaPanel.setPreferredSize(new Dimension(300, 200));
        novaContaPanel.setLayout(new GridLayout(4, 2, 5, 5));

        cpfLabel2.setText("CPF:");
        novaContaPanel.add(cpfLabel2);
        novaContaPanel.add(cpfTextField2);

        tipoContaLabel.setText("Tipo de Conta:");
        novaContaPanel.add(tipoContaLabel);

        tipoContaPanel.setLayout(new GridLayout(2, 1));

        tipoDeContaButtonGroup.add(correnteRadioButton);
        correnteRadioButton.setSelected(true);
        correnteRadioButton.setText("Conta Corrente");
        tipoContaPanel.add(correnteRadioButton);

        tipoDeContaButtonGroup.add(poupancaRadioButton);
        poupancaRadioButton.setText("Conta Poupança");
        tipoContaPanel.add(poupancaRadioButton);

        novaContaPanel.add(tipoContaPanel);

        depositoInicialLabel.setText("Depósito Inicial:");
        novaContaPanel.add(depositoInicialLabel);

        depositoInicialTextField.setToolTipText(">= 100 para Conta Poupança");
        depositoInicialTextField.addActionListener(formListener);
        novaContaPanel.add(depositoInicialTextField);
        novaContaPanel.add(vazioPanel4);

        criaButton.setText("Criar");
        criaButton.setPreferredSize(new Dimension(85, 30));
        criaPanel.add(criaButton);

        novaContaPanel.add(criaPanel);

        corpoNovaContaPanel.add(novaContaPanel);

        voltarButton2.setText("Voltar");
        voltarButton2.setPreferredSize(new Dimension(150, 30));
        corpoNovaContaPanel.add(voltarButton2);

        vazioPanel5.setPreferredSize(new Dimension(150, 10));
        corpoNovaContaPanel.add(vazioPanel5);

        tudoPanel.add(corpoNovaContaPanel, BorderLayout.CENTER);

        getContentPane().add(tudoPanel, BorderLayout.CENTER);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements ActionListener {
        FormListener() {}
        public void actionPerformed(ActionEvent evt) {
            if (evt.getSource() == depositoInicialTextField) {
                NovaConta.this.depositoInicialTextFieldActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void depositoInicialTextFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depositoInicialTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositoInicialTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel corpoNovaContaPanel;
    private JRadioButton correnteRadioButton;
    private JLabel cpfLabel2;
    private JTextField cpfTextField2;
    private JButton criaButton;
    private JPanel criaPanel;
    private JLabel depositoInicialLabel;
    private JTextField depositoInicialTextField;
    private JPanel novaContaPanel;
    private JRadioButton poupancaRadioButton;
    private JLabel tipoContaLabel;
    private JPanel tipoContaPanel;
    private ButtonGroup tipoDeContaButtonGroup;
    private JLabel tituloLabel;
    private JPanel tudoPanel;
    private JPanel vazioPanel4;
    private JPanel vazioPanel5;
    private JButton voltarButton2;
    // End of variables declaration//GEN-END:variables
}
