/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.main;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Alefe Lucas
 */
public class Operacoes extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public Operacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operacaoButtonGroup = new ButtonGroup();
        tudoPanel = new JPanel();
        tituloLabel = new JLabel();
        corpoContaPanel = new JPanel();
        contaPanel = new JPanel();
        operacaoPanel = new JPanel();
        operacaoLabel = new JLabel();
        selectOperacaoPanel = new JPanel();
        depositoRadioButton = new JRadioButton();
        saqueRadioButton = new JRadioButton();
        saldoRadioButton = new JRadioButton();
        valorPanel = new JPanel();
        valorLabel = new JLabel();
        valorTextField = new JTextField();
        vazioPanel7 = new JPanel();
        okPanel = new JPanel();
        okButton = new JButton();
        sairButton = new JButton();
        vazioPanel6 = new JPanel();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco SSA");
        setPreferredSize(new Dimension(350, 340));
        setResizable(false);

        tudoPanel.setLayout(new BorderLayout());

        tituloLabel.setHorizontalAlignment(SwingConstants.CENTER);
        tituloLabel.setIcon(new ImageIcon(getClass().getResource("/br/com/senai/main/loco SSA.png"))); // NOI18N
        tudoPanel.add(tituloLabel, BorderLayout.PAGE_START);

        contaPanel.setBorder(BorderFactory.createTitledBorder(null, "Conta:", TitledBorder.LEFT, TitledBorder.ABOVE_TOP, new Font("sansserif", 1, 18))); // NOI18N
        contaPanel.setPreferredSize(new Dimension(300, 200));
        contaPanel.setLayout(new BorderLayout());

        operacaoPanel.setLayout(new GridLayout(1, 2));

        operacaoLabel.setText("Operação:");
        operacaoPanel.add(operacaoLabel);

        selectOperacaoPanel.setLayout(new GridLayout(3, 1));

        operacaoButtonGroup.add(depositoRadioButton);
        depositoRadioButton.setSelected(true);
        depositoRadioButton.setText("Depósito");
        selectOperacaoPanel.add(depositoRadioButton);

        operacaoButtonGroup.add(saqueRadioButton);
        saqueRadioButton.setText("Saque");
        selectOperacaoPanel.add(saqueRadioButton);

        operacaoButtonGroup.add(saldoRadioButton);
        saldoRadioButton.setText("Saldo");
        selectOperacaoPanel.add(saldoRadioButton);

        operacaoPanel.add(selectOperacaoPanel);

        contaPanel.add(operacaoPanel, BorderLayout.NORTH);

        valorPanel.setLayout(new GridLayout(2, 2, 5, 5));

        valorLabel.setText("Valor:");
        valorPanel.add(valorLabel);

        valorTextField.addActionListener(formListener);
        valorPanel.add(valorTextField);
        valorPanel.add(vazioPanel7);

        okButton.setText("OK");
        okButton.setPreferredSize(new Dimension(85, 30));
        okPanel.add(okButton);

        valorPanel.add(okPanel);

        contaPanel.add(valorPanel, BorderLayout.SOUTH);

        corpoContaPanel.add(contaPanel);

        sairButton.setText("Sair");
        sairButton.setPreferredSize(new Dimension(150, 30));
        corpoContaPanel.add(sairButton);

        vazioPanel6.setPreferredSize(new Dimension(150, 10));
        corpoContaPanel.add(vazioPanel6);

        tudoPanel.add(corpoContaPanel, BorderLayout.CENTER);

        getContentPane().add(tudoPanel, BorderLayout.CENTER);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements ActionListener {
        FormListener() {}
        public void actionPerformed(ActionEvent evt) {
            if (evt.getSource() == valorTextField) {
                Operacoes.this.valorTextFieldActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void valorTextFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_valorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel contaPanel;
    private JPanel corpoContaPanel;
    private JRadioButton depositoRadioButton;
    private JButton okButton;
    private JPanel okPanel;
    private ButtonGroup operacaoButtonGroup;
    private JLabel operacaoLabel;
    private JPanel operacaoPanel;
    private JButton sairButton;
    private JRadioButton saldoRadioButton;
    private JRadioButton saqueRadioButton;
    private JPanel selectOperacaoPanel;
    private JLabel tituloLabel;
    private JPanel tudoPanel;
    private JLabel valorLabel;
    private JPanel valorPanel;
    private JTextField valorTextField;
    private JPanel vazioPanel6;
    private JPanel vazioPanel7;
    // End of variables declaration//GEN-END:variables
}
